openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for managing contacts.
tags:
  - name: Contacts
    description: Operations related to contacts.
servers:
  - url: https://nodejs-hw-mongodb-lycy.onrender.com
  - url: http://localhost:3000
paths:
  /contacts:
    get:
      tags:
        - Contacts
      summary: Get all contacts
      operationId: getAllContacts
      description: Retrieve a list of contacts for the logged-in user.
      responses:
        '200':
          description: Successfully retrieved contacts.
        '401':
          description: Unauthorized.
    post:
      tags:
        - Contacts
      summary: Create a contact
      operationId: createContact
      description: Create a new contact for the logged-in user.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                phoneNumber:
                  type: string
                email:
                  type: string
                isFavourite:
                  type: boolean
                contactType:
                  type: string
                photo:
                  type: string
                  format: binary
              required:
                - name
                - phoneNumber
                - contactType
      responses:
        '201':
          description: Successfully created contact.
        '401':
          description: Unauthorized.
  /contacts/{contactId}:
    get:
      tags:
        - Contacts
      summary: Get contact by ID
      operationId: getContactById
      description: Retrieve a contact by its ID.
      parameters:
        - name: contactId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved contact.
        '404':
          description: Contact not found.
    patch:
      tags:
        - Contacts
      summary: Update a contact
      operationId: updateContact
      description: Update an existing contact by ID.
      parameters:
        - name: contactId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                phoneNumber:
                  type: string
                email:
                  type: string
                isFavourite:
                  type: boolean
                contactType:
                  type: string
                photo:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully updated contact.
        '404':
          description: Contact not found.
    delete:
      tags:
        - Contacts
      summary: Delete a contact
      operationId: deleteContact
      description: Delete an existing contact by ID.
      parameters:
        - name: contactId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successfully deleted contact.
        '404':
          description: Contact not found.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
